version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - intoaec-network
    restart: unless-stopped

  # Backend - Python FastAPI Application
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      # Mount ML models and data
      - ./ml:/app/ml:ro
      # Mount temp directory for file processing
      - ./server/temp:/app/temp
      # Mount uploads directory
      - ./server/uploads:/app/uploads
    networks:
      - intoaec-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  intoaec-network:
    driver: bridge

volumes:
  # Persistent storage for uploads and temp files
  uploads:
  temp_files:
